import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Wrapper } from "./wrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <nav className="flex gap-4">
            <Link className="text-blue-500" href="/">
              Home
            </Link>
            <Link className="text-blue-500" href="/blog">
              Blog
            </Link>
          </nav>
        </header>
        {/* <Wrapper> */}
        {children}
        {/* </Wrapper> */}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
